{{/*
# SPDX-License-Identifier: EPL-1.0
##############################################################################
# Copyright (c) 2021 The Linux Foundation and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
##############################################################################
*/}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opendaylight.fullname" . }}-scripts
data:
{{ tpl (.Files.Glob "resources/bin/*").AsConfig . | indent 2 }}
---
{{- if .Values.config.isClusterDeployment }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opendaylight.fullname" . }}-conf
data:
{{ tpl (.Files.Glob "resources/conf/*").AsConfig . | indent 2 }}
{{- end }}