# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  # Configure VM RAM and CPU for VirtualBox
  config.vm.provider :virtualbox do |virtualbox|
    virtualbox.memory = 1024
    virtualbox.cpus = 1
  end

  # Configure VM RAM and CPU for LibVirt
  config.vm.provider :libvirt do |libvirt|
    libvirt.memory = 1024
    libvirt.cpus = 1
  end

  # Vagrantfile is for testing newly built boxes, don't spend time syncing
  config.vm.synced_folder ".", "/vagrant", disabled: true

  #
  # Vagrant definitions for supported Packer builds, for easy import/testing
  # NB: These definitions will only work after you build their respective boxes
  #

  #
  # VirtualBox
  #

  #
  # VirtualBox and CentOS
  #

  # Beryllium Release through SR4
  (0..4).each do |i|
    config.vm.define "cent_odl4#{i}_vb" do |cent_odl_vb|
      cent_odl_vb.vm.box = "cent_odl4#{i}_vb"
      cent_odl_vb.vm.box_url = "file://opendaylight-4.#{i}.0-centos-7.2.1511-virtualbox.box"
    end
  end

  # Boron Release
  (0..0).each do |i|
    config.vm.define "cent_odl5#{i}_vb" do |cent_odl_vb|
      cent_odl_vb.vm.box = "cent_odl5#{i}_vb"
      cent_odl_vb.vm.box_url = "file://opendaylight-5.#{i}.0-centos-7.2.1511-virtualbox.box"
    end
  end

  #
  # VirtualBox and Fedora 24
  #

  (0..4).each do |i|
    config.vm.define "f24_odl4#{i}_vb" do |f24_odl_vb|
      f24_odl_vb.vm.box = "f24_odl4#{i}_vb"
      f24_odl_vb.vm.box_url = "file://opendaylight-4.#{i}.0-fedora-24-virtualbox.box"
    end
  end

  (0..0).each do |i|
    config.vm.define "f24_odl5#{i}_vb" do |f24_odl_vb|
      f24_odl_vb.vm.box = "f24_odl5#{i}_vb"
      f24_odl_vb.vm.box_url = "file://opendaylight-5.#{i}.0-fedora-24-virtualbox.box"
    end
  end

  #
  # LibVirt
  #

  #
  # LibVirt and CentOS
  #

  # Beryllium Release through SR4
  (0..4).each do |i|
    config.vm.define "cent_odl4#{i}_lv" do |cent_odl_lv|
      cent_odl_lv.vm.box = "cent_odl4#{i}_lv"
      cent_odl_lv.vm.box_url = "file://opendaylight-4.#{i}.0-centos-7.2.1511-virtualbox.box"
    end
  end

  # Boron Release
  (0..0).each do |i|
    config.vm.define "cent_odl5#{i}_lv" do |cent_odl_lv|
      cent_odl_lv.vm.box = "cent_odl5#{i}_lv"
      cent_odl_lv.vm.box_url = "file://opendaylight-5.#{i}.0-centos-7.2.1511-virtualbox.box"
    end
  end

  #
  # LibVirt and Fedora 24
  #

  (0..4).each do |i|
    config.vm.define "f24_odl4#{i}_lv" do |f24_odl_lv|
      f24_odl_lv.vm.box = "f24_odl4#{i}_lv"
      f24_odl_lv.vm.box_url = "file://opendaylight-4.#{i}.0-fedora-24-virtualbox.box"
    end
  end

  (0..0).each do |i|
    config.vm.define "f24_odl5#{i}_lv" do |f24_odl_lv|
      f24_odl_lv.vm.box = "f24_odl5#{i}_lv"
      f24_odl_lv.vm.box_url = "file://opendaylight-5.#{i}.0-fedora-24-virtualbox.box"
    end
  end
end

