# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version.
VAGRANTFILE_API_VERSION = "2"

# This is a single-vm vagrant file that will install the controller and all the tools needed to run
# basic upstream CSIT
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # NFS is fragile, disable it and use rsync
  config.nfs.functional = false

  config.ssh.insert_key = false

  # Box that installs the controller VM
  config.vm.define "csit" do |csit|

    csit.vm.hostname = "csit"

    # Configure 4G RAM for virtualbox or libvirt.
    csit.vm.provider :virtualbox do |c|
      c.memory = 4096
    end
    csit.vm.provider :libvirt do |c|
      c.memory = 4096
    end

    # Build Vagrant box based on Fedora 24
    csit.vm.box = "fedora/24-cloud-base"

    # set prompt for vagrant user to match the default/expected prompt for upstream ODL CSIT
    csit.vm.provision "shell", inline: "echo 'PS1=\"[\\u@\\h \\W]> \"' >> ~vagrant/.bashrc"

    # Forward ODL's web GUI (DLUX) port so it's accessible on the host machine
    csit.vm.network "forwarded_port", guest: 8181, host: 8181

    csit.vm.network "private_network", ip: "10.10.81.21"

    # pull private "insecure" vagrant key to match the default public key that will be on each VM
    csit.vm.provision "shell",
      inline: "curl -o ~vagrant/.ssh/id_rsa https://raw.githubusercontent.com/mitchellh/vagrant/master/keys/vagrant"
    csit.vm.provision "shell", inline: "chown vagrant:vagrant ~vagrant/.ssh/id_rsa"
    csit.vm.provision "shell", inline: "chmod 0600 ~vagrant/.ssh/id_rsa"

    # Add ODL RPM repo config to correct location in box filesystem
    # Repo configs are provided by upstream OpenDaylight Integration/Packaging
    csit.vm.provision "shell",
      inline: "curl --silent -o /etc/yum.repos.d/opendaylight-42-release.repo \
               \"https://git.opendaylight.org/gerrit/gitweb?p=integration/packaging.git;a=blob_plain;f=rpm/example_repo_configs/opendaylight-42-release.repo;hb=refs/heads/master\""

    # Install ODL using the RPM repo config added above
    csit.vm.provision "shell", inline: "dnf install -y --nogpgcheck opendaylight"

    # Modify bashrc to set JAVA path
    csit.vm.provision "shell", inline: "echo 'export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.91-7.b14.fc24.x86_64/jre' >> /etc/bashrc"

    # Install dependencies
    csit.vm.provision "shell",
      inline: "dnf install -y --nogpgcheck git gcc libffi-devel openssl-devel \
                                           python-devel redhat-rpm-config python-pip \
                                           sshpass openvswitch"

    csit.vm.provision "shell",
      inline: "pip install --upgrade docker-py importlib requests scapy netifaces netaddr ipaddr \
        jsonpath-rw robotframework{,-{httplibrary,requests,sshlibrary,selenium2library}}"

    # Start Open vSwitch
    csit.vm.provision "shell", inline: "sudo /usr/share/openvswitch/scripts/ovs-ctl restart"

    # Install Mininet
    csit.vm.provision "shell", inline: "git clone git://github.com/mininet/mininet"
    csit.vm.provision "shell", inline: "cd mininet;git checkout -b 2.2.1 2.2.1;cd .."
    csit.vm.provision "shell", inline: "mininet/util/install.sh -nf"

    # Pull in Integration/Test and Releng/Builder repos
    csit.vm.provision "shell",
      inline: "git clone https://git.opendaylight.org/gerrit/p/integration/test.git"
    csit.vm.provision "shell", inline: "chown -R vagrant:vagrant ~vagrant/test"

    csit.vm.provision "shell",
      inline: "git clone https://git.opendaylight.org/gerrit/p/releng/builder.git"
    csit.vm.provision "shell", inline: "chown -R vagrant:vagrant ~vagrant/builder"

  end

end
