# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Configure VM RAM and CPU for VirtualBox
  config.vm.provider :virtualbox do |virtualbox|
    virtualbox.memory = 1024
    # Two cores over default one for faster builds
    virtualbox.cpus = 2
  end

  # Configure VM RAM and CPU for LibVirt
  config.vm.provider :libvirt do |libvirt|
    libvirt.memory = 1024
    # Two cores over default one for faster builds
    libvirt.cpus = 2
  end

  # NFS is fragile, disable it and use rsync
  config.nfs.functional = false

  # Sync folders /packaging/deb/ and /vagrant
  config.vm.synced_folder ".", "/vagrant"

  # Start from Debian VM so resulting pkgs will build on all Deb derivatives
  config.vm.box = "debian/jessie64"
  config.vm.box_version = "= 8.5.2"

  # Update package info to prevent old info from causing 404s during install
  config.vm.provision "shell", inline: "apt-get update"

  # Install pkg dev tools, Python libs for build scripts, gdebi to test install
  config.vm.provision "shell", inline: "apt-get install -y --force-yes \
                                            build-essential \
                                            devscripts \
                                            equivs \
                                            dh-systemd \
                                            python-yaml \
                                            python-jinja2 \
                                            gdebi
                                            "

  # Add jessie-backports
  config.vm.provision "shell", inline: <<-SHELL
    echo "deb http://httpredir.debian.org/debian jessie-backports main" > /etc/apt/sources.list.d/jessie-backports.list
    apt-get update
  SHELL
end
