# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # Start from Debian VM so resulting pkgs will build on all Deb derivatives
  config.vm.box = "debian/jessie64"

  # NFS is fragile, disable it and use rsync
  config.nfs.functional = false

  # Sync folders /packaging/deb/ and /vagrant
  config.vm.synced_folder ".", "/vagrant"

  # Install Debian package dev tools, helper programs for debian/rules,
  # systemd unit files, Java 7 for ODL Beryllium
  config.vm.provision "shell", inline: "apt-get install -y --force-yes \
                                            dpkg-dev \
                                            debhelper \
                                            dh-systemd \
                                            default-jdk \
                                            python-pip \
                                            "

  # Use the distribution's version of pip to upgrade to the latest pip
  config.vm.provision "shell", inline: "pip install --upgrade pip"

  # Install Python dependences system-wide via pip
  # NB: Could use a venv here, but since we're already in a Vagrant box and
  # don't need any isolation more, it doesn't seem worth the extra complexity.
  config.vm.provision "shell", inline: "pip install -r /vagrant/requirements.txt"
end
